
export enum OportunityStatusEnum {
    SEARCHING = 'SEARCHING',
    SUCCESS = 'SUCCESS',
    ERROR_ORDER1 = 'ERROR_ORDER1',
    ERROR_ORDER2 = 'ERROR_ORDER2',
    ERROR_ORDER3 = 'ERROR_ORDER3',
    ERROR_ORDER1_BLANK = 'ERROR_ORDER1_BLANK',
    ERROR_ORDER2_BLANK = 'ERROR_ORDER2_BLANK',
    ERROR_ORDER3_BLANK = 'ERROR_ORDER3_BLANK',
    ERROR_OTHER = 'ERROR_OTHER'
}
